services:
  postgres1:
    image: postgres:latest
    environment:
      POSTGRES_DB: DeliveryDB
      POSTGRES_USER: desenv
      POSTGRES_PASSWORD: password@desenv
    ports:
      - "5432:5432"
    volumes:
      - postgres1_data:/var/lib/postgresql/data

  postgres2:
    image: postgres:latest
    environment:
      POSTGRES_DB: MotorcycleDB
      POSTGRES_USER: desenv
      POSTGRES_PASSWORD: password@desenv
    ports:
      - "5433:5432"
    volumes:
      - postgres2_data:/var/lib/postgresql/data

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: desenv
      MONGO_INITDB_ROOT_PASSWORD: password@desenv
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181
    volumes:
      - zookeeper_data:/var/lib/zookeeper

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - kafka_data:/var/lib/kafka/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  minio:
    image: minio/minio
    environment:
      MINIO_ACCESS_KEY: desenv
      MINIO_SECRET_KEY: password@desenv
    command: server /data
    ports:
      - "9000:9000"
    volumes:
      - minio_data:/data

volumes:
  postgres1_data:
  postgres2_data:
  mongodb_data:
  zookeeper_data:
  kafka_data:
  redis_data:
  minio_data:
